// FIG 02 — Traditional upload vs. client upload
// Generated by gen-objgit-lfs.mjs. Do not edit by hand; change the generator.
// Static: two alternatives side by side. Green is the file's bytes, red is the egress bill.

import { AsciiFigure } from "@site/src/components/AsciiFigure";

const LINES = [
  ["  traditional upload                          client upload"],
  [],
  [
    "  ",
    ["gray", "┌──────────┐"],
    "                                ",
    ["gray", "┌──────────┐"],
    "  ",
    ["gray", "1. can I upload?"],
    "   ",
    ["gray", "┌──────────┐"],
  ],
  [
    "  ",
    ["gray", "│"],
    " client   ",
    ["gray", "│"],
    "                                ",
    ["gray", "│"],
    " client   ",
    ["gray", "│"],
    " ",
    ["gray", "──────────────────▶"],
    " ",
    ["gray", "│"],
    " your app ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "└────┬─────┘"],
    "                                ",
    ["gray", "└────┬─────┘"],
    " ",
    ["gray", "◀──────────────────"],
    " ",
    ["gray", "└──────────┘"],
  ],
  [
    "       ",
    ["green", "│"],
    " ",
    ["green", "PUT 40 MB"],
    "                                 ",
    ["green", "│"],
    "        ",
    ["gray", "2. here's a presigned URL"],
  ],
  [
    "       ",
    ["green", "▼"],
    "                                           ",
    ["green", "│"],
  ],
  [
    "  ",
    ["gray", "┌──────────┐"],
    "                                     ",
    ["green", "│"],
    " ",
    ["green", "3. PUT 40 MB, straight"],
  ],
  [
    "  ",
    ["gray", "│"],
    " your app ",
    ["gray", "│"],
    "  ",
    ["red", "egress: you pay"],
    "                    ",
    ["green", "│"],
    "    ",
    ["green", "to the bucket"],
  ],
  [
    "  ",
    ["gray", "└────┬─────┘"],
    "                                     ",
    ["green", "▼"],
  ],
  [
    "       ",
    ["green", "│"],
    " ",
    ["green", "PUT 40 MB"],
    "                            ",
    ["gray", "┌──────────┐"],
  ],
  [
    "       ",
    ["green", "▼"],
    "                                      ",
    ["gray", "│"],
    " tigris   ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "┌──────────┐"],
    "                                ",
    ["gray", "└──────────┘"],
  ],
  [
    "  ",
    ["gray", "│"],
    " tigris   ",
    ["gray", "│"],
    "                                ",
    ["gray", "your app never touches the bytes"],
  ],
  ["  ", ["gray", "└──────────┘"]],
];

export default function ClientUploads({
  label = "FIG 02",
  title = "Traditional upload vs. client upload",
  fontSize,
}) {
  return (
    <AsciiFigure
      label={label}
      title={title}
      lines={LINES}
      fontSize={fontSize}
    />
  );
}
