// FIG 05 — Verify promotes the upload and marks the repo
// Generated by gen-objgit-lfs.mjs. Do not edit by hand; change the generator.
// Static: green is the rename into the shared blob store, amber is the per-repo marker.

import { AsciiFigure } from "@site/src/components/AsciiFigure";

const LINES = [
  [
    "  POST /xe/rpg.git/info/lfs/objects/verify  ",
    ["gray", "oid 57f73e11… size 759720"],
  ],
  [],
  [
    "  ",
    ["gray", "┌─ "],
    "tigris bucket",
    ["gray", " ────────────────────────────────────────────────────┐"],
  ],
  [
    "  ",
    ["gray", "│"],
    " ",
    ["gray", "xe/rpg/lfs/staging/57f73e11…"],
    "      ",
    ["gray", "size and checksum check out"],
    "      ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    "   ",
    ["green", "│"],
    "                                                                ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    "   ",
    ["green", "│"],
    " ",
    ["green", "RenameObject: the key moves, no bytes are copied"],
    "               ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    "   ",
    ["green", "▼"],
    "                                                                ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    " ",
    ["green", "lfs/blobs/57f73e11…"],
    "               759720 bytes, stored once for    ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    "                                   every repo in the bucket         ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    "                                                                    ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    " ",
    ["amber", "xe/rpg/lfs/objects/57f73e11…"],
    "      ",
    ["amber", '0 bytes: "xe/rpg holds this"'],
    "     ",
    ["gray", "│"],
  ],
  [
    "  ",
    [
      "gray",
      "└────────────────────────────────────────────────────────────────────┘",
    ],
  ],
  [],
  [
    "  ",
    [
      "gray",
      "a clone of xe/rpg reads the marker before it gets a download URL.",
    ],
  ],
  ["  ", ["gray", "no marker, no URL, even if the blob is right there."]],
];

export default function PromoteToBlob({
  label = "FIG 05",
  title = "Verify promotes the upload and marks the repo",
  fontSize,
}) {
  return (
    <AsciiFigure
      label={label}
      title={title}
      lines={LINES}
      fontSize={fontSize}
    />
  );
}
