// FIG 01 — The row holds a name. The bucket holds the bytes.
// Generated by gen-objgit-lfs.mjs. Do not edit by hand; change the generator.
// Static: the cyan key is the pointer, green is the data it points at.

import { AsciiFigure } from "@site/src/components/AsciiFigure";

const LINES = [
  [
    "  ",
    ["gray", "┌─ "],
    "postgres: horses",
    ["gray", " ───────────┐"],
    "          ",
    ["gray", "┌─ "],
    "tigris bucket",
    ["gray", " ──────────────┐"],
  ],
  [
    "  ",
    ["gray", "│"],
    " id     42                    ",
    ["gray", "│"],
    "          ",
    ["gray", "│"],
    " ",
    ["cyan", "horses/42.jpg"],
    "                ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    " name   Butterscotch          ",
    ["gray", "│"],
    "          ",
    ["gray", "│"],
    "                              ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    " photo  ",
    ["cyan", "horses/42.jpg"],
    " ",
    ["cyan", "────────┼─────────▶"],
    ["gray", "│"],
    " ",
    ["green", "2.1 MB of horse, as a JPEG"],
    "   ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "└──────────────────────────────┘"],
    "          ",
    ["gray", "└──────────────────────────────┘"],
  ],
  [],
  [
    "  ",
    [
      "gray",
      "the database stores a short string. dereference it to get the horse.",
    ],
  ],
];

export default function RowPointsAtObject({
  label = "FIG 01",
  title = "The row holds a name. The bucket holds the bytes.",
  fontSize,
}) {
  return (
    <AsciiFigure
      label={label}
      title={title}
      lines={LINES}
      fontSize={fontSize}
    />
  );
}
