// FIG 04 — A presigned PUT with the checksum in the signature (URL-decoded)
// Generated by gen-objgit-lfs.mjs. Do not edit by hand; change the generator.
// Static: generated with dummy credentials, the same way objgit's Presigner signs. Green is the checksum.

import { AsciiFigure } from "@site/src/components/AsciiFigure";

const LINES = [
  ["  PUT https://objgit.t3.storage.dev"],
  [
    "      ",
    ["cyan", "/xe/rpg/lfs/staging/57f73e11f519…3718c84e"],
    "           ",
    ["gray", "◀ this repo's staging key"],
  ],
  ["      ?X-Amz-Algorithm=AWS4-HMAC-SHA256"],
  ["      &X-Amz-Credential=tid_EXAMPLE/20261006/auto/s3/aws4_request"],
  ["      &X-Amz-Date=20261006T193514Z"],
  [
    "      &X-Amz-Expires=900                                  ",
    ["gray", "◀ good for 15 minutes"],
  ],
  [
    "      &X-Amz-SignedHeaders=host;",
    ["green", "x-amz-checksum-sha256"],
    "     ",
    ["green", "◀ the checksum is signed"],
  ],
  ["      &x-id=PutObject"],
  ["      &X-Amz-Signature=5f6fd174…661e276a"],
  [],
  ["  ", ["gray", "the client has to send this header back, byte for byte:"]],
  [
    "      ",
    [
      "green",
      "x-amz-checksum-sha256: V/c+EfUZmUMr96sizlW2+UXV7KG/gkQEz6nsLjcYyE4=",
    ],
  ],
  [
    "                             ",
    ["gray", "└── the oid 57f73e11…c84e, in base64"],
  ],
  [],
  [
    "  ",
    [
      "gray",
      "change the header and the signature breaks. send other bytes and",
    ],
  ],
  [
    "  ",
    ["gray", "tigris rejects the PUT, because they don't hash to that value."],
  ],
];

export default function SignedChecksum({
  label = "FIG 04",
  title = "A presigned PUT with the checksum in the signature (URL-decoded)",
  fontSize,
}) {
  return (
    <AsciiFigure
      label={label}
      title={title}
      lines={LINES}
      fontSize={fontSize}
    />
  );
}
