// FIG 03 — New objects go to this repo's staging area first
// Generated by gen-objgit-lfs.mjs. Do not edit by hand; change the generator.
// Static: cyan is the presigned URL objgit hands back, green is the upload.

import { AsciiFigure } from "@site/src/components/AsciiFigure";

const LINES = [
  [
    "  ",
    ["gray", "┌───────────┐"],
    "  POST /xe/rpg.git/info/lfs/objects/batch  ",
    ["gray", "┌───────────┐"],
  ],
  [
    "  ",
    ["gray", "│"],
    " git-lfs   ",
    ["gray", "│"],
    "  upload 57f73e11…, 759720 bytes           ",
    ["gray", "│"],
    " objgit    ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    "           ",
    ["gray", "│"],
    " ",
    ["gray", "────────────────────────────────────────▶"],
    " ",
    ["gray", "│"],
    "           ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    "           ",
    ["gray", "│"],
    " ",
    ["gray", "◀────────────────────────────────────────"],
    " ",
    ["gray", "│"],
    "           ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "└────┬──────┘"],
    "  ",
    ["cyan", "PUT …/xe/rpg/lfs/staging/57f73e11…"],
    "       ",
    ["gray", "└───────────┘"],
  ],
  [
    "       ",
    ["green", "│"],
    "         ",
    ["cyan", "+ x-amz-checksum-sha256: V/c+EfUZ…"],
  ],
  [
    "       ",
    ["green", "│"],
    " ",
    ["green", "PUT 759720 bytes, straight to the bucket"],
  ],
  ["       ", ["green", "▼"]],
  [
    "  ",
    ["gray", "┌─ "],
    "tigris bucket",
    ["gray", " ────────────────────────────────────────────┐"],
  ],
  [
    "  ",
    ["gray", "│"],
    " lfs/blobs/                                                 ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    " ",
    ["green", "xe/rpg/lfs/staging/57f73e11…"],
    "  ",
    ["green", "◀── the upload lands here"],
    "    ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "│"],
    " xe/rpg/lfs/objects/                                        ",
    ["gray", "│"],
  ],
  [
    "  ",
    ["gray", "└────────────────────────────────────────────────────────────┘"],
  ],
];

export default function StagingUpload({
  label = "FIG 03",
  title = "New objects go to this repo's staging area first",
  fontSize,
}) {
  return (
    <AsciiFigure
      label={label}
      title={title}
      lines={LINES}
      fontSize={fontSize}
    />
  );
}
