// FIG 15 — the job carries its own progress
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function Checkpoints({
  label = "FIG 15",
  title = "the job carries its own progress",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"t8 — w-7 renews the lease and records where it got to"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"┌────────────────────────────────────────────────────────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f59e0b" }}>{"vest = t14"}</span>
          {"      "}
          <span style={{ color: "#64748b" }}>{"workerId: w-7"}</span>
          {"                                      "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#4ade80" }}>{"checkpoint: { bucket: \"logs-eu\", key: \"2026/09/18/03\" "}</span>
          {"}            "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"└────────────────────────────────────────────────────────────────────┘"}</span>
        </div>
        <div> </div>
        <div>
          {"  "}
          <span style={{ color: "#f87171" }}>{"t14 — w-7 dies. nobody renews the lease."}</span>
        </div>
        <div> </div>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"t20 — w-3 picks the job up and reads the checkpoint"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"┌────────────────────────────────────────────────────────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f59e0b" }}>{"vest = t26"}</span>
          {"      "}
          <span style={{ color: "#64748b" }}>{"workerId: w-3"}</span>
          {"                                      "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#4ade80" }}>{"checkpoint: { bucket: \"logs-eu\", key: \"2026/09/18/03\" "}</span>
          {"}            "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"└────────────────────────────────────────────────────────────────────┘"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// w-3 resumes the diff at 03:00 instead of re-scanning the bucket"}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// from the start. the progress lived in the queue, not the worker."}</span>
        </div>
      </pre>
    </figure>
  );
}
