// FIG 05 — the job is written by the transaction that caused it
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily:
    "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Fira Code VF', monospace",
  fontVariantLigatures: "none",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function EnqueueInTxn({
  label = "FIG 05",
  title = "the job is written by the transaction that caused it",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"   "}
          <span style={{ color: "#64748b" }}>{"t1"}</span>
          {"                        "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "──┬─────────────────────────┬────────────────────────────────────────────▶"
            }
          </span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {"                         "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#4ade80" }}>{"└─ PutObject commits."}</span>
          {"     "}
          <span style={{ color: "#f59e0b" }}>{"└─ vestingMs reached."}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#4ade80" }}>{"the same txn writes"}</span>
          {"       "}
          <span style={{ color: "#f59e0b" }}>{"a range scan can"}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#4ade80" }}>{"the gc job at t2"}</span>
          {"          "}
          <span style={{ color: "#f59e0b" }}>{"see it now"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {
              "// the object and the job land together or not at all. there is no"
            }
          </span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {"// second system to keep in sync, so there is no dual write."}
          </span>
        </div>
      </pre>
    </figure>
  );
}
