// FIG 18 — sharded lanes, and what happens when a worker dies
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function HashringLanes({
  label = "FIG 18",
  title = "sharded lanes, and what happens when a worker dies",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"queue · one key per job, checkpoint in the body"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"┌──────────────────────────────────────────────────────────────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"[a91f ck:03]"}</span>
          {"  "}
          <span style={{ color: "#64748b" }}>{"[b17c ck:—]"}</span>
          {"  "}
          <span style={{ color: "#64748b" }}>{"[c04e ck:7f]"}</span>
          {"  "}
          <span style={{ color: "#64748b" }}>{"[d22a ck:—]"}</span>
          {"  "}
          <span style={{ color: "#64748b" }}>{"[e90b ck:11]"}</span>
          {"       "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"└───────┬───────────────────┬───────────────────┬───────────────────┬──────┘"}</span>
        </div>
        <div>
          {"          "}
          <span style={{ color: "#60a5fa" }}>{"│ lease"}</span>
          {"             "}
          <span style={{ color: "#60a5fa" }}>{"│ lease"}</span>
          {"             "}
          <span style={{ color: "#60a5fa" }}>{"│ lease"}</span>
          {"             "}
          <span style={{ color: "#60a5fa" }}>{"▲ checkpoint"}</span>
        </div>
        <div>
          {"          "}
          <span style={{ color: "#60a5fa" }}>{"▼"}</span>
          {"                   "}
          <span style={{ color: "#60a5fa" }}>{"▼"}</span>
          {"                   "}
          <span style={{ color: "#60a5fa" }}>{"▼"}</span>
          {"                   "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"┌─────────────────┐"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"┌─────────────────┐"}</span>
          {" "}
          <span style={{ color: "#475569" }}>{"┌─────────────────┐"}</span>
          {" "}
          <span style={{ color: "#475569" }}>{"┌─────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"lane 0"}</span>
          {"          "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"lane 1"}</span>
          {"          "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"lane 2"}</span>
          {"          "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"lane 3"}</span>
          {"          "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"w-7"}</span>
          {"   [■][■]    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"w-9"}</span>
          {"   [■][■]    "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"w-3"}</span>
          {"   [■]       "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"w-5"}</span>
          {"   [■][■]    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"└─────────────────┘"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"└───────┬─────────┘"}</span>
          {" "}
          <span style={{ color: "#475569" }}>{"└─────────────────┘"}</span>
          {" "}
          <span style={{ color: "#475569" }}>{"└─────────────────┘"}</span>
        </div>
        <div>
          {"                              "}
          <span style={{ color: "#f87171" }}>{"│ w-9 stops renewing"}</span>
        </div>
        <div>
          {"                              "}
          <span style={{ color: "#f87171" }}>{"▼"}</span>
        </div>
        <div>
          {"                              "}
          <span style={{ color: "#f87171" }}>{"its two jobs vest again, hash into new lanes,"}</span>
        </div>
        <div>
          {"                              "}
          <span style={{ color: "#f87171" }}>{"and w-3 and w-5 pick them up on the next scan"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// hash(key) picks the lane. claiming a job changes vestingMs,"}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// which changes the key, which changes the lane. no worker and"}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// no lane stays unlucky for long."}</span>
        </div>
      </pre>
    </figure>
  );
}
