// FIG 02 — two producers both decide they are number 67
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function IdCollision({
  label = "FIG 02",
  title = "two producers both decide they are number 67",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"producer A"}</span>
          {"                                "}
          <span style={{ color: "#64748b" }}>{"producer B"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#4ade80" }}>{"┌────────────────────────────────┐"}</span>
          {"        "}
          <span style={{ color: "#f87171" }}>{"┌────────────────────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#4ade80" }}>{"read counter → 66"}</span>
          {"              "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {"        "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"read counter → 66"}</span>
          {"              "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#4ade80" }}>{"write ('q',67)"}</span>
          {"                 "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {"        "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"write ('q',67)"}</span>
          {"                 "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#4ade80" }}>{"└───────────────┬────────────────┘"}</span>
          {"        "}
          <span style={{ color: "#f87171" }}>{"└───────────────┬────────────────┘"}</span>
        </div>
        <div>
          {"                  "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {"                                         "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
        </div>
        <div>
          {"                  "}
          <span style={{ color: "#475569" }}>{"└────────────────────┬────────────────────┘"}</span>
        </div>
        <div>
          {"                                       "}
          <span style={{ color: "#475569" }}>{"▼"}</span>
        </div>
        <div>
          {"                    "}
          <span style={{ color: "#475569" }}>{"┌──────────────────────────────────────┐"}</span>
        </div>
        <div>
          {"                    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" one key. the second write either     "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"                    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" overwrites the first job, or the txn "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"                    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" conflicts and somebody retries.      "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"                    "}
          <span style={{ color: "#475569" }}>{"└──────────────────────────────────────┘"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// so you encode randomness into the key. now the order is a lie."}</span>
        </div>
      </pre>
    </figure>
  );
}
