// FIG 09 — the job finishes and deletes itself
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function JobCompletes({
  label = "FIG 09",
  title = "the job finishes and deletes itself",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"   "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
          {"                  "}
          <span style={{ color: "#64748b" }}>{"t4"}</span>
          {"                          "}
          <span style={{ color: "#64748b" }}>{"t8"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"──┬───────────────────┬───────────────────────────┬──────────────────────▶"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {"                   "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {"                           "}
          <span style={{ color: "#64748b" }}>{"│"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#60a5fa" }}>{"└─ leased"}</span>
          {"           "}
          <span style={{ color: "#4ade80" }}>{"└─ work done."}</span>
          {"               "}
          <span style={{ color: "#64748b" }}>{"└─ lease would"}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#60a5fa" }}>{"by w-7"}</span>
          {"              "}
          <span style={{ color: "#4ade80" }}>{"w-7 clears"}</span>
          {"                  "}
          <span style={{ color: "#64748b" }}>{"have expired"}</span>
        </div>
        <div>
          {"                           "}
          <span style={{ color: "#4ade80" }}>{"the key"}</span>
          {"                     "}
          <span style={{ color: "#64748b" }}>{"here"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// finishing is the only way a job leaves the queue."}</span>
        </div>
      </pre>
    </figure>
  );
}
