// FIG 07 — the two ways a leased job ends
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function JobOutcomes({
  label = "FIG 07",
  title = "the two ways a leased job ends",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>
            {"w-7 holds a91f with vest = t8. there are two ways this ends."}
          </span>
        </div>
        <div> </div>
        <div>
          {"   "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
          {"                  "}
          <span style={{ color: "#64748b" }}>{"t4"}</span>
          {"                            "}
          <span style={{ color: "#64748b" }}>{"t8"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "──┬───────────────────┬─────────────────────────────┬────────────────────▶"
            }
          </span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#64748b" }}>{"│"}</span>
          {"                   "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {"                             "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#64748b" }}>{"└─ leased by w-7"}</span>
          {"    "}
          <span style={{ color: "#4ade80" }}>{"├─ A: the work finishes"}</span>
          {"       "}
          <span style={{ color: "#4ade80" }}>{"├─ A: nothing to expire"}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#64748b" }}>{"vest = t8"}</span>
          {"           "}
          <span style={{ color: "#4ade80" }}>{"w-7 clears the key"}</span>
          {"            "}
          <span style={{ color: "#4ade80" }}>{"the job is gone"}</span>
        </div>
        <div>
          {"                        "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {"                             "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
        </div>
        <div>
          {"                        "}
          <span style={{ color: "#f87171" }}>{"└─ B: w-7 is OOM killed"}</span>
          {"       "}
          <span style={{ color: "#f59e0b" }}>{"└─ B: t8 is now the past"}</span>
        </div>
        <div>
          {"                           "}
          <span style={{ color: "#f87171" }}>{"the key is untouched"}</span>
          {"          "}
          <span style={{ color: "#f59e0b" }}>{"w-3 scans it up"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {"// finishing is the only way a job leaves the queue. crashing"}
          </span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {"// costs one lease period and nothing else."}
          </span>
        </div>
      </pre>
    </figure>
  );
}
