// FIG 04 — a QuiCK key, field by field
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function KeyAnatomy({
  label = "FIG 04",
  title = "a QuiCK key, field by field",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>
            {'("queue", version, taskType, itemSpace, vestingMs, priority, id)'}
          </span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"        │"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"        └──▶ QueueItem"}</span>
        </div>
        <div> </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "┌─────────────┬──────────────────────────────────────────────────────────┐"
            }
          </span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#f59e0b" }}>{"vestingMs"}</span>
          {"   "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#f59e0b" }}>
            {"when the job may run. this is the sort key."}
          </span>
          {"              "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "├─────────────┼──────────────────────────────────────────────────────────┤"
            }
          </span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" taskType    "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>
            {"which queue. gc, lifecycle, replication."}
          </span>
          {"                 "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" itemSpace   "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>
            {"the tenant or bucket the job belongs to"}
          </span>
          {"                  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" priority    "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>
            {"ordering inside one vesting millisecond"}
          </span>
          {"                  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" id          "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>
            {"random suffix, so two producers never collide"}
          </span>
          {"            "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "└─────────────┴──────────────────────────────────────────────────────────┘"
            }
          </span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {
              "// identity is mostly a timestamp. that one choice is the whole trick."
            }
          </span>
        </div>
      </pre>
    </figure>
  );
}
