// FIG 09 — a lease is a clear and a set
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function LeaseWrite({
  label = "FIG 09",
  title = "a lease is a clear and a set",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "┌──────────────────────────────────────────────────────────────────────┐"
            }
          </span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>
            {'("queue",1,"gc","bkt-42",'}
          </span>
          <span style={{ color: "#f59e0b" }}>{"1758500000000"}</span>
          <span style={{ color: "#64748b" }}>{',0,"a91f")'}</span>{" "}
          <span style={{ color: "#64748b" }}>{"→"}</span>{" "}
          <span style={{ color: "#64748b" }}>{"workerId: null"}</span>
          {"    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "└──────────────────────────────────────────────────────────────────────┘"
            }
          </span>
        </div>
        <div>
          {"                            "}
          <span style={{ color: "#60a5fa" }}>
            {"│  w-7 leases it, in one transaction"}
          </span>
        </div>
        <div>
          {"                            "}
          <span style={{ color: "#60a5fa" }}>{"▼"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "┌──────────────────────────────────────────────────────────────────────┐"
            }
          </span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>
            {'("queue",1,"gc","bkt-42",'}
          </span>
          <span style={{ color: "#f59e0b" }}>{"1758500030000"}</span>
          <span style={{ color: "#64748b" }}>{',0,"a91f")'}</span>{" "}
          <span style={{ color: "#64748b" }}>{"→"}</span>{" "}
          <span style={{ color: "#4ade80" }}>{'workerId: "w-7"'}</span>
          {"   "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "└──────────────────────────────────────────────────────────────────────┘"
            }
          </span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {
              "// vestingMs is part of the key, so a lease physically moves the row"
            }
          </span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {
              "// 30 seconds into the future and stamps it with whoever owns it."
            }
          </span>
        </div>
      </pre>
    </figure>
  );
}
