// FIG 13 — a long job keeps moving its own deadline
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function LeaseRenewal({
  label = "FIG 13",
  title = "a long job keeps moving its own deadline",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"   "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
          {"           "}
          <span style={{ color: "#64748b" }}>{"t8"}</span>
          {"           "}
          <span style={{ color: "#64748b" }}>{"t14"}</span>
          {"          "}
          <span style={{ color: "#64748b" }}>{"t20"}</span>
          {"          "}
          <span style={{ color: "#64748b" }}>{"t26"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"──┬────────────┬────────────┬────────────┬────────────┬──────────────────▶"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {"            "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {"            "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {"            "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {"            "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#60a5fa" }}>{"lease"}</span>
          {"        "}
          <span style={{ color: "#60a5fa" }}>{"renew"}</span>
          {"        "}
          <span style={{ color: "#60a5fa" }}>{"renew"}</span>
          {"        "}
          <span style={{ color: "#60a5fa" }}>{"renew"}</span>
          {"        "}
          <span style={{ color: "#4ade80" }}>{"done"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#64748b" }}>{"w-7"}</span>
          {"          "}
          <span style={{ color: "#64748b" }}>{"w-7"}</span>
          {"          "}
          <span style={{ color: "#64748b" }}>{"w-7"}</span>
          {"          "}
          <span style={{ color: "#64748b" }}>{"w-7"}</span>
          {"          "}
          <span style={{ color: "#4ade80" }}>{"cleared"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// while a worker keeps checking in, nobody else can see the job."}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// stop checking in and it vests again, whatever the reason was."}</span>
        </div>
      </pre>
    </figure>
  );
}
