// FIG 08 — claiming a job by pushing it into the future
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function LeaseClaim({
  label = "FIG 08",
  title = "claiming a job by pushing it into the future",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"   "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
          {"                                              "}
          <span style={{ color: "#64748b" }}>{"t8"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"──┬───────────────────────────────────────────────┬──────────────────────▶"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {"                                               "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#60a5fa" }}>{"└─ w-7 scans [0, now] and"}</span>
          {"                       "}
          <span style={{ color: "#f59e0b" }}>{"└─ the lease runs"}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#60a5fa" }}>{"picks this job. rewrites"}</span>
          {"                        "}
          <span style={{ color: "#f59e0b" }}>{"out here"}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#60a5fa" }}>{"the key with vest = t8"}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#60a5fa" }}>{"and workerId = w-7"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// there is no claim flag and no lock table. the job's own key is"}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// the lease, and the deadline is part of its name."}</span>
        </div>
      </pre>
    </figure>
  );
}
