// FIG 01 — the queue every FoundationDB tutorial builds
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function NaiveQueue({
  label = "FIG 01",
  title = "the queue every FoundationDB tutorial builds",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"consumer"}</span>
          {"                                          "}
          <span style={{ color: "#64748b" }}>{"producer"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#60a5fa" }}>{"┌────────────────────────┐"}</span>
          {"                        "}
          <span style={{ color: "#4ade80" }}>{"┌────────────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {" range scan the front   "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {"                        "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {" set the next key       "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {" clear what you read    "}
          <span style={{ color: "#60a5fa" }}>{"│"}</span>
          {"                        "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {" at the back            "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#60a5fa" }}>{"└─────┬──────────────────┘"}</span>
          {"                        "}
          <span style={{ color: "#4ade80" }}>{"└───────┬────────────────┘"}</span>
        </div>
        <div>
          {"        "}
          <span style={{ color: "#60a5fa" }}>{"▼"}</span>
          {"                                                   "}
          <span style={{ color: "#4ade80" }}>{"▼"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"┌──────────────────────────────────────────────────────────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"(\"q\",1)"}</span>
          {"   "}
          <span style={{ color: "#64748b" }}>{"(\"q\",2)"}</span>
          {"   "}
          <span style={{ color: "#64748b" }}>{"(\"q\",3)"}</span>
          {"   "}
          <span style={{ color: "#64748b" }}>{"(\"q\",4)"}</span>
          {"   "}
          <span style={{ color: "#64748b" }}>{"…"}</span>
          {"     "}
          <span style={{ color: "#64748b" }}>{"(\"q\",65)"}</span>
          {"   "}
          <span style={{ color: "#64748b" }}>{"(\"q\",66)"}</span>
          {"    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"└──────────────────────────────────────────────────────────────────────┘"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"front of the keyspace"}</span>
          {"                             "}
          <span style={{ color: "#64748b" }}>{"back of the keyspace"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// pop from one end, push to the other. reading an item deletes it."}</span>
        </div>
      </pre>
    </figure>
  );
}
