// FIG 02 — time, when nobody is arguing about it
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function OneClock({
  label = "FIG 02",
  title = "time, when nobody is arguing about it",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"time"}</span>
        </div>
        <div>
          {"   "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"t1"}</span>{" "}
          <span style={{ color: "#475569" }}>{"├──▶"}</span>
          {"  "}
          <span style={{ color: "#4ade80" }}>{"person picks up apple"}</span>
        </div>
        <div>
          {"   "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"t2"}</span>{" "}
          <span style={{ color: "#475569" }}>{"├──▶"}</span>
          {"  "}
          <span style={{ color: "#4ade80" }}>{"person eats apple"}</span>
        </div>
        <div>
          {"   "}
          <span style={{ color: "#475569" }}>{"▼"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {"// one clock, one observer. the order you saw is the order it"}
          </span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {"// happened. distributed systems do not get this for free."}
          </span>
        </div>
      </pre>
    </figure>
  );
}
