// FIG 01 — a pop is a delete, and a delete is forever
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily:
    "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Fira Code VF', monospace",
  fontVariantLigatures: "none",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function PopDestroys({
  label = "FIG 01",
  title = "a pop is a delete, and a delete is forever",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"   "}
          <span style={{ color: "#64748b" }}>{"t1"}</span>
          {"                    "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
          {"                    "}
          <span style={{ color: "#64748b" }}>{"t3"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {
              "──┬─────────────────────┬─────────────────────┬──────────────────────────▶"
            }
          </span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#64748b" }}>{"│"}</span>
          {"                     "}
          <span style={{ color: "#64748b" }}>{"│"}</span>
          {"                     "}
          <span style={{ color: "#64748b" }}>{"│"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#60a5fa" }}>{"└─ worker pops"}</span>
          {"        "}
          <span style={{ color: "#f87171" }}>{"└─ row gone from"}</span>
          {"      "}
          <span style={{ color: "#f87171" }}>{"└─ worker dies"}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#60a5fa" }}>{"('q',1)"}</span>
          {"               "}
          <span style={{ color: "#f87171" }}>{"FoundationDB"}</span>
          {"          "}
          <span style={{ color: "#f87171" }}>{"mid-PutObject"}</span>
        </div>
        <div> </div>
        <div>
          {"  "}
          <span style={{ color: "#f87171" }}>
            {
              "┌──────────────────────────────────────────────────────────────────┐"
            }
          </span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#f87171" }}>{"│"}</span>{" "}
          <span style={{ color: "#f87171" }}>
            {"nothing in the database remembers that ('q',1) existed."}
          </span>
          {"          "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#f87171" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>
            {"the replication job for uploads/report.pdf is simply gone."}
          </span>
          {"       "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#f87171" }}>
            {
              "└──────────────────────────────────────────────────────────────────┘"
            }
          </span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {
              "// a user in Frankfurt cannot see an object written in Chicago, and"
            }
          </span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {"// there is no record left anywhere that tells you why."}
          </span>
        </div>
      </pre>
    </figure>
  );
}
