// FIG 07 — the only exit from the wheel is finishing
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily:
    "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Fira Code VF', monospace",
  fontVariantLigatures: "none",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function Samsara({
  label = "FIG 07",
  title = "the only exit from the wheel is finishing",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"┌──────────────────┐"}</span>
          {"    "}
          <span style={{ color: "#475569" }}>{"┌──────────────────┐"}</span>
          {"    "}
          <span style={{ color: "#f87171" }}>
            {"┌────────────────────────┐"}
          </span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>{"vested"}</span>
          {"           "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          <span style={{ color: "#64748b" }}>{"──▶"}</span>{" "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>{"leased by w-7"}</span>
          {"    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          <span style={{ color: "#f87171" }}>{"──▶"}</span>{" "}
          <span style={{ color: "#f87171" }}>{"│"}</span>{" "}
          <span style={{ color: "#f87171" }}>{"w-7 crashed"}</span>
          {"            "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"└───────┬──────────┘"}</span>
          {"    "}
          <span style={{ color: "#475569" }}>{"└───────┬──────────┘"}</span>
          {"    "}
          <span style={{ color: "#f87171" }}>
            {"└──────────┬─────────────┘"}
          </span>
        </div>
        <div>
          {"          "}
          <span style={{ color: "#f59e0b" }}>{"▲"}</span>
          {"                       "}
          <span style={{ color: "#4ade80" }}>{"│ finishes"}</span>
          {"                 "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
        </div>
        <div>
          {"          "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
          {"                       "}
          <span style={{ color: "#4ade80" }}>{"▼"}</span>
          {"                          "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
        </div>
        <div>
          {"          "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
          {"               "}
          <span style={{ color: "#4ade80" }}>{"┌──────────────────┐"}</span>
          {"               "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
        </div>
        <div>
          {"          "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
          {"               "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>{" "}
          <span style={{ color: "#4ade80" }}>{"cleared"}</span>
          {"          "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
          {"               "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
        </div>
        <div>
          {"          "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
          {"               "}
          <span style={{ color: "#4ade80" }}>{"└──────────────────┘"}</span>
          {"               "}
          <span style={{ color: "#f59e0b" }}>{"│"}</span>
        </div>
        <div>
          {"          "}
          <span style={{ color: "#f59e0b" }}>
            {"└───────── lease expires, job vests again ─────────┘"}
          </span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {
              "// crashing does not remove a job. it puts it back on the wheel one"
            }
          </span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {"// lease period later, for whichever worker shows up next."}
          </span>
        </div>
      </pre>
    </figure>
  );
}
