// FIG 03 — the same two events, observed out of order
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily:
    "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Fira Code VF', monospace",
  fontVariantLigatures: "none",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function TwoFrames({
  label = "FIG 03",
  title = "the same two events, observed out of order",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"RF1 · next to the apple"}</span>
          {"                           "}
          <span style={{ color: "#64748b" }}>{"RF2 · reads the tweets"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {"┌──────────────────────────┐"}
          </span>
          {"                      "}
          <span style={{ color: "#475569" }}>
            {"┌──────────────────────────┐"}
          </span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>{"t1"}</span>
          {"  "}
          <span style={{ color: "#4ade80" }}>{"picks up apple"}</span>
          {"       "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {"  "}
          <span style={{ color: "#60a5fa" }}>{"── tweet ──▶"}</span>
          {"        "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>{"t3"}</span>
          {"  "}
          <span style={{ color: "#f87171" }}>{'reads "eats apple"'}</span>
          {"   "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
          {"  "}
          <span style={{ color: "#4ade80" }}>{"eats apple"}</span>
          {"           "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {"  "}
          <span style={{ color: "#60a5fa" }}>{"── tweet ──▶"}</span>
          {"        "}
          <span style={{ color: "#475569" }}>{"│"}</span>{" "}
          <span style={{ color: "#64748b" }}>{"t4"}</span>
          {"  "}
          <span style={{ color: "#f87171" }}>{'reads "picks up"'}</span>
          {"     "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>
            {"└──────────────────────────┘"}
          </span>
          {"                      "}
          <span style={{ color: "#475569" }}>
            {"└──────────────────────────┘"}
          </span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {
              "// the first tweet was slow. RF2 believes the apple was eaten and"
            }
          </span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>
            {"// then picked up. attach the observed time, or live with this."}
          </span>
        </div>
      </pre>
    </figure>
  );
}
