// FIG 14 — the cost of putting the queue in the database
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function TxnConflict({
  label = "FIG 14",
  title = "the cost of putting the queue in the database",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#64748b" }}>{"worker w-7"}</span>
          {"                              "}
          <span style={{ color: "#64748b" }}>{"worker w-9"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"┌──────────────────────────────┐"}</span>
          {"        "}
          <span style={{ color: "#475569" }}>{"┌──────────────────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" scan [0, now]                "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {"        "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" scan [0, now]                "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"→ sees job a91f"}</span>
          {"              "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {"        "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"→ sees job a91f"}</span>
          {"              "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" clear + set vest = t8        "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {"        "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" clear + set vest = t8        "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"└──────────────┬───────────────┘"}</span>
          {"        "}
          <span style={{ color: "#475569" }}>{"└──────────────┬───────────────┘"}</span>
        </div>
        <div>
          {"                 "}
          <span style={{ color: "#f87171" }}>{"└───────────────────┬───────────────────┘"}</span>
        </div>
        <div>
          {"                                     "}
          <span style={{ color: "#f87171" }}>{"▼"}</span>
        </div>
        <div>
          {"                  "}
          <span style={{ color: "#f87171" }}>{"┌──────────────────────────────────────┐"}</span>
        </div>
        <div>
          {"                  "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"FoundationDB: read-write conflict."}</span>
          {"   "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
        </div>
        <div>
          {"                  "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"one txn commits, one retries."}</span>
          {"        "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
        </div>
        <div>
          {"                  "}
          <span style={{ color: "#f87171" }}>{"└──────────────────────────────────────┘"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// the paper's answer is a coin flip: each worker only reaches for"}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// some of the jobs it can see, so fewer of them collide."}</span>
        </div>
      </pre>
    </figure>
  );
}
