// FIG 17 — what a coin flip does to the job nobody picks
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function UnluckyJob({
  label = "FIG 17",
  title = "what a coin flip does to the job nobody picks",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"┌────────┬──────────────────────────────────────────────────────────────┐"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"job"}</span>
          {"    "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
          {"      "}
          <span style={{ color: "#64748b" }}>{"t8"}</span>
          {"      "}
          <span style={{ color: "#64748b" }}>{"t14"}</span>
          {"     "}
          <span style={{ color: "#64748b" }}>{"t20"}</span>
          {"     "}
          <span style={{ color: "#64748b" }}>{"t26"}</span>
          {"     "}
          <span style={{ color: "#64748b" }}>{"t32"}</span>
          {"                  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"├────────┼──────────────────────────────────────────────────────────────┤"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" b17c   "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#4ade80" }}>{"taken"}</span>
          {"                                                        "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" c04e   "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#64748b" }}>{"skip"}</span>
          {"    "}
          <span style={{ color: "#4ade80" }}>{"taken"}</span>
          {"                                                "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"a91f"}</span>
          {"   "}
          <span style={{ color: "#475569" }}>{"│"}</span>
          {" "}
          <span style={{ color: "#f87171" }}>{"skip"}</span>
          {"    "}
          <span style={{ color: "#f87171" }}>{"skip"}</span>
          {"    "}
          <span style={{ color: "#f87171" }}>{"skip"}</span>
          {"    "}
          <span style={{ color: "#f87171" }}>{"skip"}</span>
          {"    "}
          <span style={{ color: "#f87171" }}>{"skip"}</span>
          {"    "}
          <span style={{ color: "#f87171" }}>{"skip"}</span>
          {"                 "}
          <span style={{ color: "#475569" }}>{"│"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"└────────┴──────────────────────────────────────────────────────────────┘"}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// six workers at a 20% pick rate. the coin has no memory of how"}</span>
        </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// long a91f has waited, so it can sit there for minutes."}</span>
        </div>
      </pre>
    </figure>
  );
}
