// FIG 10 — when the worker dies, the job does not
// Generated by var/quick-fdb-kafka-diagrams.mjs. Do not edit by hand.

const PRE_STYLE = {
  margin: "0",
  background: "#0f172a",
  border: "1px solid #16202f",
  borderRadius: "6px",
  padding: "32px",
  overflowX: "auto",
  lineHeight: "1.3",
  color: "#cbd5e1",
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  fontSize: "13px",
  whiteSpace: "pre",
  textAlign: "left",
};

export default function WorkerCrash({
  label = "FIG 10",
  title = "when the worker dies, the job does not",
  showHeader = true,
  fontSize,
}) {
  const preStyle = fontSize ? { ...PRE_STYLE, fontSize } : PRE_STYLE;
  return (
    <figure
      style={{
        margin: 0,
        display: "flex",
        flexDirection: "column",
        gap: 10,
        textAlign: "left",
      }}
    >
      {showHeader && (
        <figcaption
          style={{
            display: "flex",
            alignItems: "baseline",
            gap: 14,
            fontFamily: PRE_STYLE.fontFamily,
          }}
        >
          <span
            style={{ fontSize: 11, color: "#475569", letterSpacing: "0.14em" }}
          >
            {label}
          </span>
          <span style={{ fontSize: 12, color: "#94a3b8" }}>{title}</span>
        </figcaption>
      )}
      <pre style={preStyle}>
        <div>
          {"   "}
          <span style={{ color: "#64748b" }}>{"t2"}</span>
          {"                  "}
          <span style={{ color: "#64748b" }}>{"t3"}</span>
          {"                          "}
          <span style={{ color: "#64748b" }}>{"t8"}</span>
        </div>
        <div>
          {"  "}
          <span style={{ color: "#475569" }}>{"──┬───────────────────┬───────────────────────────┬──────────────────────▶"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#64748b" }}>{"│"}</span>
          {"                   "}
          <span style={{ color: "#f87171" }}>{"│"}</span>
          {"                           "}
          <span style={{ color: "#4ade80" }}>{"│"}</span>
        </div>
        <div>
          {"    "}
          <span style={{ color: "#64748b" }}>{"└─ leased"}</span>
          {"           "}
          <span style={{ color: "#f87171" }}>{"└─ w-7 is OOM"}</span>
          {"               "}
          <span style={{ color: "#4ade80" }}>{"└─ vest = t8 is now"}</span>
        </div>
        <div>
          {"       "}
          <span style={{ color: "#64748b" }}>{"vest = t8"}</span>
          {"           "}
          <span style={{ color: "#f87171" }}>{"killed. the key"}</span>
          {"             "}
          <span style={{ color: "#4ade80" }}>{"in the past again."}</span>
        </div>
        <div>
          {"                           "}
          <span style={{ color: "#f87171" }}>{"is untouched"}</span>
          {"                "}
          <span style={{ color: "#4ade80" }}>{"w-3 picks it up."}</span>
        </div>
        <div> </div>
        <div>
          <span style={{ color: "#64748b" }}>{"// worst case you wait one lease period. you never lose the work."}</span>
        </div>
      </pre>
    </figure>
  );
}
